# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitorC.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emonitorC.proto\"\x17\n\x07Request\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"$\n\x13MemoryUsageResponse\x12\r\n\x05usage\x18\x01 \x01(\x05\x32{\n\x08MonitorC\x12/\n\tGetStatus\x12\x0f.StatusResponse\x1a\x0f.StatusResponse\"\x00\x12>\n\x0eGetMemoryUsage\x12\x14.MemoryUsageResponse\x1a\x14.MemoryUsageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitorC_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=18
  _REQUEST._serialized_end=41
  _STATUSRESPONSE._serialized_start=43
  _STATUSRESPONSE._serialized_end=75
  _MEMORYUSAGERESPONSE._serialized_start=77
  _MEMORYUSAGERESPONSE._serialized_end=113
  _MONITORC._serialized_start=115
  _MONITORC._serialized_end=238
# @@protoc_insertion_point(module_scope)
