version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 80:80
    restart: always
    networks:
      - status_red
    container_name: app_instance

  monitor:
    build:
      context: .
      dockerfile: Dockerfile-monitorc
    ports:
      - 50051:50051
    restart: always
    networks:
      - status_red
    container_name: monitorc