# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitorC_pb2 as monitorC__pb2


class MonitorCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/MonitorC/GetStatus',
                request_serializer=monitorC__pb2.Request.SerializeToString,
                response_deserializer=monitorC__pb2.StatusResponse.FromString,
                )
        self.GetMemoryUsage = channel.unary_unary(
                '/MonitorC/GetMemoryUsage',
                request_serializer=monitorC__pb2.Request.SerializeToString,
                response_deserializer=monitorC__pb2.MemoryUsageResponse.FromString,
                )


class MonitorCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemoryUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=monitorC__pb2.Request.FromString,
                    response_serializer=monitorC__pb2.StatusResponse.SerializeToString,
            ),
            'GetMemoryUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemoryUsage,
                    request_deserializer=monitorC__pb2.Request.FromString,
                    response_serializer=monitorC__pb2.MemoryUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MonitorC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MonitorC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MonitorC/GetStatus',
            monitorC__pb2.Request.SerializeToString,
            monitorC__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMemoryUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MonitorC/GetMemoryUsage',
            monitorC__pb2.Request.SerializeToString,
            monitorC__pb2.MemoryUsageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
